name: udangtan_flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  flutter_dotenv: ^5.1.0
  kakao_map_plugin: ^0.3.7
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  http: ^1.2.2
  supabase_flutter: ^2.8.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash-image.png
  android: true
  ios: true
  web: true
  branding: null
  fullscreen: true
